/*DELETE FROM FUNCIONARIOS;*/
/*SELECT * FROM FUNCIONARIOS;*/
/*SELECT * FROM TabelaPontos*/
/*SELECT * FROM EMPREGADOR*/


CREATE TABLE FUNCIONARIOS (
    cpf VARCHAR(15) PRIMARY KEY,
    email VARCHAR(100),
    nome VARCHAR(100),
    senha VARCHAR(255),
    EMPREGADOR VARCHAR(100),
    data_contratacao VARCHAR(12),
    funcao VARCHAR(100)
);


CREATE TABLE TabelaPontos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cpf VARCHAR(15),
    email VARCHAR(100),
    hora VARCHAR(100),
    data_ponto VARCHAR(12),
    FOREIGN KEY (cpf) REFERENCES FUNCIONARIOS(cpf) ON DELETE CASCADE
);

CREATE TABLE EMPREGADOR(
    id INT AUTO_INCREMENT PRIMARY KEY,
    senha VARCHAR(255),
    email VARCHAR(100),
    cpf VARCHAR(15),
    nome VARCHAR(100),
    empresa VARCHAR(100)
)
